### ISSUE TITLE
Regular expressions aren’t the right way

### ISSUE THREAD

**Issue by charmander** [danmactough/node-resanitize#2]
As a simple example, try `stripUnsafeTags` on this:

```
<<<form></form>form></form>form method="POST" action="/delete" id="bad"><<input>input type="hidden" name="id" value="100"><<script></script>script>document.getElementById("bad").submit();</script></</form>form>
```

**Comment by charmander** [comment]
Blacklists also aren’t the right way. The `<script>` vulerability already breaks everything, but apart from that, `oninput` is also missing from your event list. Combined with `contenteditable` on a simple `<div>`, there’s another script injection.

That regular expression is also not restrictive enough; `<div onclick="anything"foo="bar">` makes it through `stripUnsafeAttrs` unchanged.

**Comment by charmander** [comment]
I also don’t see any protection against `<a href="javascript:anything">Click me!</a>`.

**Comment by charmander** [comment]
On an unrelated note, why does `stripComments` exist and why doesn’t it strip comments?

**Comment by danmactough** [comment]
Thanks for the good comments. I've addressed each of them in `v0.2.0` to the extent I think is worthwhile given the limited scope of this module. Any pointers to more robust javascript tools to use when appropriate are welcome.

**Comment by charmander** [comment]
Ah, my apologies. A more robust way would be:
- An HTML parser — whichever type is most convenient
- A whitelist of tags and attributes instead of a blacklist — both have received (and likely, in the future, will receive) additions

So a new vulnerability, then:

``` html
<a href="javascript&#58;anything">Click me!</a>
```

There are probably more, but by fixing all of these as they come, you _will_ end up with an HTML parser, but implemented using regular expressions. And you won’t really know whether it works properly.

Bonus vulnerability: `vbscript:`, `livescript:` protocols. I strongly recommend (apart from the previous strong recommendations) that you take a look at [the OWASP XSS Filter Evasion Cheat Sheet](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet), at the very least.

**Comment by charmander** [comment]
This one especially; it’s truly fun.

``` html
<IMG """><SCRIPT>alert("XSS")</SCRIPT>">
```
